# Generated by Django 4.2.14 on 2024-08-16 14:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alpha2_code', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('--', 'Undefined'), ('NC', 'News Channel'), ('AB', "Author's Blog"), ('AN', 'Anonymous Channel'), ('OC', 'Official Channel'), ('OK', 'Other')], default='--', max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=128)),
                ('last_parsed_post', models.IntegerField(default=0)),
                ('first_parsed_post', models.IntegerField(default=0)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.country')),
            ],
        ),
        migrations.CreateModel(
            name='PostEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemmatized_name', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PostKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PostLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('spacy_model_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tag_template', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('--', 'Undefined'), ('TT', 'Text'), ('TV', 'Video'), ('TO', 'Other')], default='--', max_length=2)),
                ('header', models.TextField()),
                ('text', models.TextField()),
                ('post_id', models.IntegerField(default=0)),
                ('time_posted', models.DateTimeField()),
                ('time_parsed', models.DateTimeField()),
                ('time_pipelined', models.DateTimeField()),
                ('pipelined', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newschannel')),
                ('entities', models.ManyToManyField(blank=True, to='news.postentity')),
                ('hashtags', models.ManyToManyField(blank=True, to='news.posthashtag')),
                ('keywords', models.ManyToManyField(blank=True, to='news.postkeyword')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.postlanguage')),
            ],
        ),
        migrations.AddField(
            model_name='newschannel',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.socialmedia'),
        ),
    ]
