# Generated by Django 4.2.14 on 2024-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='time_pipelined',
            field=models.DateTimeField(null=True),
        ),
    ]
