# Generated by Django 4.2.14 on 2024-08-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('editor', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_end', models.DateField(default=django.utils.timezone.now)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('channels', models.ManyToManyField(blank=True, to='news.newschannel')),
                ('countries', models.ManyToManyField(blank=True, to='news.country')),
                ('entities', models.ManyToManyField(blank=True, to='news.postentity')),
                ('hashtags', models.ManyToManyField(blank=True, to='news.posthashtag')),
                ('keywords', models.ManyToManyField(blank=True, to='news.postkeyword')),
                ('language', models.ManyToManyField(blank=True, to='news.postlanguage')),
                ('socials', models.ManyToManyField(blank=True, to='news.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
